### PR TITLE
Added `BlendPreset::Invert`

### LINKED ISSUE #16: Add `BlendPreset::Invert`
This can be used to draw areas with inverted colors. The source color controls which color components appears inverted. Alpha channel remains the same. By modifying `value` after setting preset one can control the base color. Drawing a white shape will do normal invert of colors.

``` Rust
state::Blend {
  color: state::BlendChannel {
    equation: state::Equation::Sub,
    source: state::Factor::ZeroPlus(state::BlendValue::ConstColor),
    destination: state::Factor::ZeroPlus(state::BlendValue::SourceColor),
  },
  alpha: state::BlendChannel {
    equation: state::Equation::Add,
    source: state::Factor::Zero,
    destination: state::Factor::One,
  },
  value: [1.0, 1.0, 1.0, 1.0],
}
```

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/gfx-rs/draw_state/issues/16

### CODE REVIEW

**Comment by kvark** [comment]
Is it a common case at all? I haven't seen it being used.
Please give me an example.

**Comment by bvssvni** [comment]
A couple examples:
- In widget and editor programming it is a way to achieve "select effect" to guarantee the selection will be clearly visible, independently on background (for example, toolbar)
- Imagine processing and image editors uses this a lot

I use this even more often than multiplicative blending. There are more ways to get plain invert blending, so we have to pick one of them. I picked the one that was most conceptually clear to me what happened when I tweaked the values.

**Comment by kvark** [comment]
Ok, I do see the "select effect" being a good case, but image processing/editors do inverting as a custom case of a more powerful (shader-based) framework, so the shortcut is not really needed there. Merging!

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
