### PR TITLE
Redesign `Factor`

### LINKED ISSUE #8: Redesign `Factor` and `BlendValue`, remove `InverseFlag`
Change `Factor` into an enum and move over `Zero`, `One` and `SourceAlphaSaturated`:

``` rust
pub enum BlendValue {
    SourceColor,
    SourceAlpha,
    DestColor,
    DestAlpha,
    ConstColor,
    ConstAlpha,
}

pub enum Factor {
    Zero,
    One,
    SourceAlphaSaturated,
    ZeroPlus(BlendValue),
    OneMinus(BlendValue),
}
```

This will get rid of `InverseFlag` and will remove the invalid state `Factor(InverseFlag::Inverse, BlendValue::SourceAlphaSaturated)`.

Example:

```
source: block::Factor(InverseFlag::Normal, BlendValue::SourceAlpha)
source: block::Factor(InverseFlag::Inverse, BlendValue::Zero)
```

becomes

```
source: block::Factor::ZeroPlus(BlendValue::SourceAlpha)
source: block::Factor::One
```

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/gfx-rs/draw_state/issues/8

### CODE REVIEW

**Comment by kvark** [comment]
I like this!

**Comment by brendanzab** [comment]
Nice!

**Comment by bvssvni** [comment]
Rust is going through some breaking changes now, so I'll wait with merging until things have settled down a bit...

**Comment by bvssvni** [comment]
Rebased.

I'm trying to use gfx_examples to check which parts that gets affected, but getting blocked by https://github.com/bjz/glfw-rs/issues/304

**Comment by bvssvni** [comment]
The issue is fixed now.

**Comment by bvssvni** [comment]
Still having problems with gfx_examples, but I'll make a PR for gfx_device_gl.

**Comment by bvssvni** [comment]
Looks good. Merging.

**Pull request merged**
