### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by bvssvni**
- Bumped to 0.2.0

### CODE REVIEW

**Comment by kvark** [comment]
I guess there is no harm in this.

@homu r+

**Comment by kvark** [comment]
@homu r+

**Comment by kvark** [comment]
Ah, homu is not in this project, gotcha.

**Comment by bvssvni** [comment]
@kvark I'm working on a tool to make updating easier called "Eco" https://github.com/pistondevelopers/eco. This PR is based on information discovered by Eco which otherwise would have gone unnoticed. It found the same issue in rust-sdl2. I plan to add more Gfx libraries so we can keep larger parts of the ecosystem updated.

**Comment by kvark** [comment]
Oh neat!

Regards,
Dzmitry

**Comment by bvssvni** [comment]
Can we merge this or do you want to set up homu first?

**Comment by kvark** [comment]
Proceed with merge please

**Pull request merged**
